### ISSUE TITLE
assignment 4 for grading

### ISSUE THREAD

**Issue by ChenyuWClaire** [VIS-2129-F2020/cwang2-vis#4]
Hi, the map looks fine in rstudio but was corrupted when knitted... 
https://vis-2129-f2020.github.io/cwang2-vis/assignment4

**Comment by c-voulgaris** [comment]
That's strange - it knits just fine when I run your code from my computer, and the basemap in the knitted file doesn't look cartolight (from the colors). Are you sure you knitted after your most recent edits to the Rmd file? You may want to try knitting again.

This looks like it was finished and submitted in a hurry, and it's your choice if you don't want to spend any more time on it, but if you have time to make some quick changes, your grade may improve a little. It isn't due until Wednesday.

In case you want to revise this further before the submission deadline:

Remove the html-style line breaks (`<br/>` from lines 11, 12, 14, and 15, and just replace them with empty spaces so that the heading on line 13 gets formatted right.

You should add headings and text throughout to explain what your doing and what your graphs show.

Line 68: Add `results='hide'` so that all those lines of graph-building output don't get printed to your html file

Line 137: Move this to the top of your file - you should load all your libraries at the beginning. Also - you don't need to use the reshape2 package (although you can). You could just use the `pivot_longer()` function in the dplyr package (the reverse of the `pivot_wider()` function you use on line 122. Or, you could replace lines 119 - 122 with:
```
long_iso_areas <- iso_all_modes %>%
  mutate(area = st_area(iso_all_modes)) %>%
  st_set_geometry(NULL) %>%  
  mutate(area = as.numeric(area))

wide_iso_areas <- iso_all_modes %>%
  mutate(area = st_area(iso_all_modes)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 
```
The replace line 124 with `ggplot(iso_areas, `, delete lines 136 - 141, and replace line 142 with `ggplot(wide_iso_areas, `

**Comment by ChenyuWClaire** [comment]
Some how still can't get those in-between messy lines disappear even with the results="hide", message=F, warning=F...

**Comment by bauranov** [comment]
When mesage=FALSE... doesn't work, try adding this code at the beginning of the rmarkdown:
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, warning = FALSE, results = "hide", message = FALSE)
```

Other than that, great work!
